version: "3.9"

services:
  db:
    environment:
      - POSTGRES_PASSWORD

  api:
    image: "ghcr.io/03b8/dcb_berlin_guide_backend:${TAG:-latest}"
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 berlin_guide.wsgi:application
    expose:
      - "8000"
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DEBUG: "${DEBUG:-false}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      CORS_ALLOW_ALL_ORIGINS: "${CORS_ALLOW_ALL_ORIGINS}"
      SECRET_KEY: "${SECRET_KEY}"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`${BERLIN_GUIDE_DOMAIN?Variable not set}`) && PathPrefix(`/api/`) || PathPrefix(`/admin/`) || PathPrefix(`/django-static/`)"
        - "traefik.http.routers.api.entrypoints=http"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik-public"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik-public
      - default

  webapp:
    image: "ghcr.io/03b8/dcb_berlin_guide_frontend:${TAG:-latest}"
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webapp.rule=Host(`${BERLIN_GUIDE_DOMAIN?Variable not set}`) && PathPrefix(`/`) "
        - "traefik.http.routers.webapp.entrypoints=http"
        - "traefik.http.services.webapp.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik-public
      - default

  reverse-proxy:
    image: "traefik:v2.4"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      resources:
        limits:
          memory: "128MB"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reverse-proxy.rule=Host(`${BERLIN_GUIDE_DOMAIN?Variable not set}`)"
        - "traefik.http.services.reverse-proxy.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmmode"
      - "--entrypoints.http.address=:80"
      - "--api"
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
    external: true
