version: "3.3"

services:
  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secretpassword}"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  api:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secretpassword}"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      DEBUG: "true"
      ALLOWED_HOSTS: "*"
      CORS_ALLOW_ALL_ORIGINS: "true"
    volumes:
      - ./backend:/backend

  webapp:
    volumes:
    - ./frontend/src:/src
    environment:
      REACT_APP_MAPBOX_TOKEN: "${REACT_APP_MAPBOX_TOKEN}"
      REACT_APP_API_URL: "${REACT_APP_API_URL}"
